### ISSUE TITLE
can you provide quiz solutions 

### ISSUE THREAD

**Issue by gitosam** [goutham7r/Deep-Learning-in-Computer-Vision#1]

**Comment by gagandeep1504** [comment]
yes i want to work in this

**Comment by gitosam** [comment]
Thanku for your response but I've completed my course.

**Comment by tranvansanghust** [comment]
@gitosam, @gagandeep1504  Do you have free time. Because I have to complete the course by Sep, 20. So, Please help me to review my assignments:
Week2: https://www.coursera.org/learn/deep-learning-in-computer-vision/peer/STsNv/facial-keypoints-notebook/review/jdm2Gfb_Eeq0VArkASuwDw
Week3: https://www.coursera.org/learn/deep-learning-in-computer-vision/peer/8MWx2/face-detection-notebook/review/enmv1vb_EeqK6w7Z5Kuhgw
Week4: https://www.coursera.org/learn/deep-learning-in-computer-vision/peer/dFypQ/face-recognition-notebook/review/lk4B__cVEeq9SA6hJWNb9Q
Week5: https://www.coursera.org/learn/deep-learning-in-computer-vision/peer/9h2K8/gan-notebook/review/n92qDfcrEeq0VArkASuwDw

Thanks!
